// src/generators/generateAdminFiles.ts
import fs from "fs-extra";
import path from "path";
import {
  permissionMatrixTemplate,
  routeManifestTemplate,
} from "../templates/generatedFiles";
import {
  usePermissionTemplate,
  useRoleTemplate,
  useAuthTemplate,
} from "../templates/hooks";
import { protectedRouteTemplate, canTemplate } from "../templates/components";

export interface GenerateOptions {
  cwd: string;
  srcDir: string;
  roles: string[];
  projectName: string;
}

export async function generateAdminFiles(opts: GenerateOptions) {
  const adminDir = path.join(opts.cwd, opts.srcDir, "admin");

  // ── directory structure ───────────────────────────────────
  await fs.ensureDir(path.join(adminDir, "_generated"));
  await fs.ensureDir(path.join(adminDir, "hooks"));
  await fs.ensureDir(path.join(adminDir, "components", "guards"));
  await fs.ensureDir(path.join(adminDir, "components", "layout"));
  await fs.ensureDir(path.join(adminDir, "pages"));

  // ── _generated/ ──────────────────────────────────────────
  // Empty matrix to start — ron sync fills it from config
  const emptyMatrix = Object.fromEntries(opts.roles.map((r) => [r, []]));

  await fs.writeFile(
    path.join(adminDir, "_generated", "permission-matrix.ts"),
    permissionMatrixTemplate(emptyMatrix),
  );

  await fs.writeFile(
    path.join(adminDir, "_generated", "route-manifest.ts"),
    routeManifestTemplate(opts.roles),
  );

  // ── hooks/ ────────────────────────────────────────────────
  await fs.writeFile(
    path.join(adminDir, "hooks", "useAuth.ts"),
    useAuthTemplate,
  );
  await fs.writeFile(
    path.join(adminDir, "hooks", "usePermission.ts"),
    usePermissionTemplate,
  );
  await fs.writeFile(
    path.join(adminDir, "hooks", "useRole.ts"),
    useRoleTemplate,
  );

  // ── guards/ ───────────────────────────────────────────────
  await fs.writeFile(
    path.join(adminDir, "components", "guards", "ProtectedRoute.tsx"),
    protectedRouteTemplate,
  );
  await fs.writeFile(
    path.join(adminDir, "components", "guards", "Can.tsx"),
    canTemplate,
  );

  // ── pages/ ────────────────────────────────────────────────
  await fs.writeFile(
    path.join(adminDir, "pages", "DashboardPage.tsx"),
    `// Generated by Ron CLI — you own this file, edit freely

export function DashboardPage() {
  return (
    <div className="p-8">
      <h1 className="text-2xl font-bold text-gray-900">
        Dashboard
      </h1>
      <p className="mt-2 text-gray-500">
        Welcome to ${opts.projectName}
      </p>
    </div>
  );
}
`,
  );

  // ── index.tsx ────────────────────────────────────────────
  await fs.writeFile(
    path.join(adminDir, "index.tsx"),
    `// Generated by Ron CLI — you own this file, edit freely
import { Routes, Route }     from "react-router-dom";
import { ProtectedRoute }    from "./components/guards/ProtectedRoute";
import { DashboardPage }     from "./pages/DashboardPage";

export function AdminRouter() {
  return (
    <Routes>
      <Route
        path="/admin"
        element={
          <ProtectedRoute>
            <DashboardPage />
          </ProtectedRoute>
        }
      />
    </Routes>
  );
}
`,
  );
}
