// src/vite/codegen.ts
import type { RonRoute } from "../types";

/**
 * Generates the virtual module content for ron/routes.
 * This is what gets imported by <RonRouter />.
 */
export function generateRoutesModule(routes: RonRoute[]): string {
  // Find root layout — the _layout.tsx at the pages root
  const rootLayout = routes.find((r) => r.layoutPath)?.layoutPath;

  const rootLayoutImport = rootLayout
    ? `const RootLayout = lazy(() => import(${JSON.stringify(rootLayout)}));`
    : "";

  const imports = routes
    .map(
      (route, i) =>
        `const Page${i} = lazy(() => import(${JSON.stringify(route.filePath)}));`,
    )
    .join("\n");

  const routeObjects = routes
    .map(
      (route, i) => `  {
    path:       ${JSON.stringify(route.path)},
    component:  Page${i},
    permission: ${JSON.stringify(route.permission ?? null)},
    isDynamic:  ${route.isDynamic},
    params:     ${JSON.stringify(route.params)},
  }`,
    )
    .join(",\n");

  return `
// ⚡ AUTO-GENERATED by @ronjs/router Vite plugin
import { lazy } from "react";

${rootLayoutImport}
${imports}

export const rootLayout = ${rootLayout ? "RootLayout" : "undefined"};

export const routes = [
${routeObjects}
];

export default routes;
`.trim();
}
