// src/vite/codegen.ts
import type { RonRoute } from "../types";

/**
 * Generates the virtual module content for ron/routes.
 * This is what gets imported by <RonRouter />.
 */
export function generateRoutesModule(routes: RonRoute[]): string {
  const imports = routes
    .map((route, i) => {
      const lines: string[] = [];
      lines.push(
        `const Page${i} = lazy(() => import(${JSON.stringify(route.filePath)}));`,
      );
      if (route.layoutPath) {
        lines.push(
          `const Layout${i} = lazy(() => import(${JSON.stringify(route.layoutPath)}));`,
        );
      }
      return lines.join("\n");
    })
    .join("\n");

  const routeObjects = routes
    .map((route, i) => {
      return `  {
    path:       ${JSON.stringify(route.path)},
    component:  Page${i},
    layout:     ${route.layoutPath ? `Layout${i}` : "undefined"},
    permission: ${JSON.stringify(route.permission ?? null)},
    isDynamic:  ${route.isDynamic},
    params:     ${JSON.stringify(route.params)},
  }`;
    })
    .join(",\n");

  return `
// ⚡ AUTO-GENERATED by @ron/router Vite plugin
// Do not edit manually

import { lazy } from "react";

${imports}

export const routes = [
${routeObjects}
];

export default routes;
`.trim();
}
