// src/templates/components.ts

export const protectedRouteTemplate = `// Generated by Ron CLI — you own this file, edit freely
import { Navigate, useLocation } from "react-router-dom";
import { useAuth }       from "../hooks/useAuth";
import { usePermission } from "../hooks/usePermission";
import type { Permission } from "../_generated/permission-matrix";

interface ProtectedRouteProps {
  permission?:  Permission | Permission[];
  requireAll?:  boolean;
  fallback?:    React.ReactNode;
  children:     React.ReactNode;
}

export function ProtectedRoute({
  permission,
  requireAll = false,
  fallback,
  children,
}: ProtectedRouteProps) {
  const { user, isLoading } = useAuth();
  const location            = useLocation();

  const hasAccess = usePermission(
    permission ?? [],
    requireAll
  );

  if (isLoading) {
    return (
      <div className="flex h-screen items-center justify-center">
        <div className="h-8 w-8 animate-spin rounded-full border-4 border-blue-500 border-t-transparent" />
      </div>
    );
  }

  if (!user) {
    return <Navigate to="/login" replace state={{ from: location }} />;
  }

  if (permission && !hasAccess) {
    if (fallback) return <>{fallback}</>;
    return <Navigate to="/403" replace />;
  }

  return <>{children}</>;
}
`;

export const canTemplate = `// Generated by Ron CLI — you own this file, edit freely
import { usePermission } from "../hooks/usePermission";
import type { Permission } from "../_generated/permission-matrix";

interface CanProps {
  permission:  Permission | Permission[];
  requireAll?: boolean;
  fallback?:   React.ReactNode;
  children:    React.ReactNode;
}

export function Can({
  permission,
  requireAll = false,
  fallback   = null,
  children,
}: CanProps) {
  const hasAccess = usePermission(permission, requireAll);
  return hasAccess ? <>{children}</> : <>{fallback}</>;
}
`;
