// src/templates/generatedFiles.ts

export function permissionMatrixTemplate(
  matrix: Record<string, string[]>,
): string {
  const entries = Object.entries(matrix)
    .map(([role, perms]) => {
      const permsStr = perms.map((p) => `"${p}"`).join(", ");
      return `  ${role}: [${permsStr}] as const,`;
    })
    .join("\n");

  return `// ⚠️  AUTO-GENERATED by Ron CLI — do not edit manually
// Re-run \`ron sync\` to update after changing admin.config.ts
// Generated: ${new Date().toISOString()}

export const PERMISSION_MATRIX = {
${entries}
} as const;

export type Role =
  keyof typeof PERMISSION_MATRIX;

export type Permission =
  typeof PERMISSION_MATRIX[Role][number];
`;
}

export function routeManifestTemplate(roles: string[]): string {
  return `// ⚠️  AUTO-GENERATED by Ron CLI — do not edit manually
// Re-run \`ron sync\` to update after changing admin.config.ts
// Generated: ${new Date().toISOString()}

export const ROLES = [${roles.map((r) => `"${r}"`).join(", ")}] as const;

export const ROUTE_MANIFEST = {
  root: "/admin",
  // Routes are added here as you define resources in admin.config.ts
} as const;
`;
}
