// src/templates/hooks.ts

export const usePermissionTemplate = `// Generated by Ron CLI — you own this file, edit freely
import { useAuth } from "./useAuth";
import type { Permission } from "../_generated/permission-matrix";

export function usePermission(
  required:   Permission | Permission[],
  requireAll: boolean = false
): boolean {
  const { user } = useAuth();
  if (!user) return false;

  const perms = Array.isArray(required) ? required : [required];

  return requireAll
    ? perms.every((p) => user.permissions.includes(p))
    : perms.some((p)  => user.permissions.includes(p));
}
`;

export const useRoleTemplate = `// Generated by Ron CLI — you own this file, edit freely
import { useAuth } from "./useAuth";
import type { Role } from "../_generated/permission-matrix";

export function useRole(...roles: Role[]): boolean {
  const { user } = useAuth();
  return Boolean(user && roles.includes(user.role as Role));
}
`;

export const useAuthTemplate = `// Generated by Ron CLI — you own this file, edit freely
// Replace this stub with your actual auth implementation

export interface RonUser {
  id:          string;
  role:        string;
  permissions: string[];
}

interface AuthContext {
  user:      RonUser | null;
  isLoading: boolean;
}

// TODO: Replace with your real auth hook (Clerk, NextAuth, Supabase, etc.)
export function useAuth(): AuthContext {
  // Example with Clerk:
  // const { user, isLoaded } = useUser();
  // return { user: user ? { id: user.id, role: user.publicMetadata.role, permissions: [] } : null, isLoading: !isLoaded };

  return {
    user:      null,
    isLoading: false,
  };
}
`;
