export const topbarStyles = {
  ".ron-topbar": {
    height: "4rem",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "0 1rem",
    gap: "1rem",
    backgroundColor: "var(--ron-surface)",
    borderBottom: "1px solid var(--ron-border)",
    flexShrink: "0",
  },
  ".ron-topbar-title": {
    fontSize: "0.9375rem",
    fontWeight: "600",
    color: "var(--ron-text)",
  },
  ".ron-avatar": {
    width: "1.75rem",
    height: "1.75rem",
    borderRadius: "9999px",
    backgroundColor: "var(--ron-primary)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: "0",
    fontSize: "0.75rem",
    fontWeight: "600",
    color: "var(--ron-primary-fg)",
  },
  ".ron-dropdown": {
    position: "absolute",
    right: "0",
    top: "calc(100% + 0.25rem)",
    width: "12rem",
    backgroundColor: "var(--ron-surface)",
    border: "1px solid var(--ron-border)",
    borderRadius: "var(--ron-radius-lg)",
    boxShadow: "var(--ron-shadow-md)",
    zIndex: "50",
    overflow: "hidden",
  },
  ".ron-dropdown-item": {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
    padding: "0.5rem 0.75rem",
    fontSize: "0.875rem",
    color: "var(--ron-text)",
    cursor: "pointer",
    border: "none",
    width: "100%",
    textAlign: "left",
    backgroundColor: "transparent",
    transition: "background-color 150ms",
    "&:hover": {
      backgroundColor: "var(--ron-surface-hover)",
    },
  },
  ".ron-dropdown-item-danger": {
    color: "var(--ron-danger)",
    "&:hover": {
      backgroundColor: "var(--ron-danger-bg)",
    },
  },
};
